init debian packages install

diff --git a/usr/bin/bds-install b/usr/bin/bds-install
--- a/usr/bin/bds-install
+++ b/usr/bin/bds-install
@@ -1,96 +1,230 @@
 #!/bin/bash
-source progress_bar.sh
-if [[ -e /etc/debian_version ]]; then
-	source /etc/os-release
-	OS=$ID # debian or ubuntu
-else
-	echo "Você não tem instalado ou não esta com sistema Debian ou Ubuntu "
-	exit 1
-fi
-if [ "$(uname -m)" = "x86_64" ];then
-    echo "Processador (X64) AMD64, continuando"
-else
-    echo "Seu processador não é uma AMD64 (X64) ele é um $(uname -m)"
-    exit 1
-fi
-
-REMOVE=$(pwd)
-
-#Usuario
 
 
-#Root
-if [ "$EUID" -ne 0 ]; then
-	echo "Você não está executando o script com root ou sudo"
-	exit 0
-fi
-if [[ $OS == 'ubuntu' ]]; then
-    echo "Ubuntu detectado instalando algumas recomendações espere ..."
-       apt install screen unzip dos2unix jq zip net-tools -y >>$USUARIO/log.txt 2>&1 ;
-elif [[ $OS == 'debian' ]]; then
-	 apt install screen unzip zip dos2unix jq net-tools -y >>$USUARIO/log.txt 2>&1 ;
-else
-      exit 1
-fi
 
 
-#pode ser aqui ali ou DEBIAN
-TMP=/home/Minecraft-temp
- mkdir $TMP >>$USUARIO/log.txt 2>&1 ;
+# inclusão do progess bar direto no bds-install ---------------------------------------
 
-# Remoção dos arquivo de log
- rm -rf $TMP/level.txt >>$USUARIO/log.txt 2>&1 ;
+# https://github.com/pollev/bash_progress_bar - See license at end of file
 
-echo "o Diretorio do seu usuario é $USUARIO"
-echo "Começamos ás $(TZ=UTC+3 date +"%H:%M:%S")"
-echo " "
-echo "--------------"
-echo " "
+# Usage:
+# Source this script
+# enable_trapping <- optional to clean up properly if user presses ctrl-c
+# setup_scroll_area <- create empty progress bar
+# draw_progress_bar 10 <- advance progress bar
+# draw_progress_bar 40 <- advance progress bar
+# block_progress_bar 45 <- turns the progress bar yellow to indicate some action is requested from the user
+# draw_progress_bar 90 <- advance progress bar
+# destroy_scroll_area <- remove progress bar
+
+# Constants
+CODE_SAVE_CURSOR="\033[s"
+CODE_RESTORE_CURSOR="\033[u"
+CODE_CURSOR_IN_SCROLL_AREA="\033[1A"
+COLOR_FG="\e[30m"
+COLOR_BG="\e[42m"
+COLOR_BG_BLOCKED="\e[43m"
+RESTORE_FG="\e[39m"
+RESTORE_BG="\e[49m"
+
+# Variables
+PROGRESS_BLOCKED="false"
+TRAPPING_ENABLED="false"
+TRAP_SET="false"
+
+setup_scroll_area() {
+    # If trapping is enabled, we will want to activate it whenever we setup the scroll area and remove it when we break the scroll area
+    if [ "$TRAPPING_ENABLED" = "true" ]; then
+        trap_on_interrupt
+    fi
+
+    lines=$(tput lines)
+    let lines=$lines-1
+    # Scroll down a bit to avoid visual glitch when the screen area shrinks by one row
+    echo -en "\n"
+
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+    # Set scroll region (this will place the cursor in the top left)
+    echo -en "\033[0;${lines}r"
+
+    # Restore cursor but ensure its inside the scrolling area
+    echo -en "$CODE_RESTORE_CURSOR"
+    echo -en "$CODE_CURSOR_IN_SCROLL_AREA"
+
+    # Start empty progress bar
+    draw_progress_bar 0
+}
+
+destroy_scroll_area() {
+    lines=$(tput lines)
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+    # Set scroll region (this will place the cursor in the top left)
+    echo -en "\033[0;${lines}r"
+
+    # Restore cursor but ensure its inside the scrolling area
+    echo -en "$CODE_RESTORE_CURSOR"
+    echo -en "$CODE_CURSOR_IN_SCROLL_AREA"
+
+    # We are done so clear the scroll bar
+    clear_progress_bar
+
+    # Scroll down a bit to avoid visual glitch when the screen area grows by one row
+    echo -en "\n\n"
+
+    # Once the scroll area is cleared, we want to remove any trap previously set. Otherwise, ctrl+c will exit our shell
+    if [ "$TRAP_SET" = "true" ]; then
+        trap - INT
+    fi
+}
+
+draw_progress_bar() {
+    percentage=$1
+    lines=$(tput lines)
+    let lines=$lines
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # Clear progress bar
+    tput el
+
+    # Draw progress bar
+    PROGRESS_BLOCKED="false"
+    print_bar_text $percentage
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+block_progress_bar() {
+    percentage=$1
+    lines=$(tput lines)
+    let lines=$lines
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # Clear progress bar
+    tput el
+
+    # Draw progress bar
+    PROGRESS_BLOCKED="true"
+    print_bar_text $percentage
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+clear_progress_bar() {
+    lines=$(tput lines)
+    let lines=$lines
+    # Save cursor
+    echo -en "$CODE_SAVE_CURSOR"
+
+    # Move cursor position to last row
+    echo -en "\033[${lines};0f"
+
+    # clear progress bar
+    tput el
+
+    # Restore cursor position
+    echo -en "$CODE_RESTORE_CURSOR"
+}
+
+print_bar_text() {
+    local percentage=$1
+    local cols=$(tput cols)
+    let bar_size=$cols-17
+
+    local color="${COLOR_FG}${COLOR_BG}"
+    if [ "$PROGRESS_BLOCKED" = "true" ]; then
+        color="${COLOR_FG}${COLOR_BG_BLOCKED}"
+    fi
+
+    # Prepare progress bar
+    let complete_size=($bar_size*$percentage)/100
+    let remainder_size=$bar_size-$complete_size
+    progress_bar=$(echo -ne "["; echo -en "${color}"; printf_new "#" $complete_size; echo -en "${RESTORE_FG}${RESTORE_BG}"; printf_new "." $remainder_size; echo -ne "]");
+
+    # Print progress bar
+    echo -ne " Progress ${percentage}% ${progress_bar}"
+}
+
+enable_trapping() {
+    TRAPPING_ENABLED="true"
+}
+
+trap_on_interrupt() {
+    # If this function is called, we setup an interrupt handler to cleanup the progress bar
+    TRAP_SET="true"
+    trap cleanup_on_interrupt INT
+}
+
+cleanup_on_interrupt() {
+    destroy_scroll_area
+    exit
+}
+
+printf_new() {
+    str=$1
+    num=$2
+    v=$(printf "%-${num}s" "$str")
+    echo -ne "${v// /$str}"
+}
+
+
+# SPDX-License-Identifier: MIT
+#
+# Copyright (c) 2018--2020 Polle Vanhoof
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
+
+
 
 # --------------- Codigo ------------------------------
 
-
-variaveis_predefinidas(){
-BDS="$(wget -qO- https://script.sirherobrine23.org/BDS.txt)"
-echo "Atualmente temos os sequinte link download: $BDS"
-USUARIO=$(echo $HOME)
-if [[ -e installed.txt ]]; then
-      PATH_TO_INSTALL="$(cat installed.txt)" 
-      echo "Depois voçê pode alterar o diretorio no arquivo 'installed.txt'"
-      echo " "
-      echo " "
-else
-      read -rp "a onde vai ser instalado: " -e -i "/home/minecraft" PATH_TO_INSTALL
-      touch installed.txt -a $PATH_TO_INSTALL
-      echo "$PATH_TO_INSTALL" >> installed.txt
-      echo " "
-      echo " "
+root_acess(){
+if [ "$EUID" -ne 0 ]; then
+echo "Você não está executando o script com root ou sudo, por favor execute de novo o com: sudo $0 $1"
+exit 0
 fi
-
-cat $PATH_TO_INSTALL/server.properties | grep "level-name=" > /tmp/level.txt ; sed -i "s|level-name=||g" "/tmp/level.txt"
-    level=$(dos2unix /tmp/port.txt;cat /tmp/level.txt)
-    read -rp "Qual é o nome do Mapa (Só confimação do nome): " -e -i "$level" MAPA_DO_SERVIDOR
-    cat $PATH_TO_INSTALL/server.properties | grep "server-port=" > /tmp/port.txt ; sed -i "s|server-port=||g" "/tmp/port.txt"
-    PORTAD=$(dos2unix /tmp/port.txt;cat /tmp/port.txt)
-
 }
+
+TMP=/tmp/Minecraft-temp
+mkdir $TMP >>$USUARIO/log.txt 2>&1 ;
+rm -rf $TMP/level.txt >>$USUARIO/log.txt 2>&1 ;
+PASTA_PRINCIPAL=/usr/opt/bds-install
+
 
 json(){
-     PATH_TO_INSTALL="$(cat install.json | jq ".install.dir" | sed 's|"||g')"
-     BDS="$(wget -qO- $(cat install.json | jq ".global.url_download" | sed 's|"||g'))"
-     PORTAD="$(cat install.json | jq ".global.port" | sed 's|"||g')"
-     MAPA_DO_SERVIDOR="$(cat install.json | jq ".global.name_map" | sed 's|"||g')"
-     level="$(cat install.json | jq ".global.name_map" | sed 's|"||g')"
+     PATH_TO_INSTALL="$(cat /etc/bds-install/install.json | jq ".install.dir" | sed 's|"||g')"
+     BDS="$(wget -qO- $(cat /etc/bds-install/install.json | jq ".global.url_download" | sed 's|"||g'))"
+     PORTAD="$(cat /etc/bds-install/install.json | jq ".global.port" | sed 's|"||g')"
+     MAPA_DO_SERVIDOR="$(cat /etc/bds-install/install.json | jq ".global.name_map" | sed 's|"||g')"
+     level="$(cat /etc/bds-install/install.json | jq ".global.name_map" | sed 's|"||g')"
 }
-
-# Usando arquivo json
-
-if [[ -e install.json ]];then
-json
-else
-variaveis_predefinidas
-fi
-
 limpando(){
     rm mcpe.zip
     rm -rf mcpe/
@@ -106,20 +240,20 @@ installbysh23(){
 draw_progress_bar 1
     #Download do arquivos servidor
     echo "Baixando o Software do BDS";
-     wget "$BDS" -O mcpe.zip >>$USUARIO/log.txt 2>&1 ;
+     wget "$BDS" -O $TMP/mcpe.zip >>$USUARIO/log.txt 2>&1 ;
 draw_progress_bar 2
     echo "Descompactando o software do BDS";
     draw_progress_bar 5
-     unzip mcpe.zip -d mcpe/ >>$USUARIO/log.txt 2>&1 ;
-     rm -rf mcpe.zip;
+     unzip $TMP/mcpe.zip -d $TMP/mcpe/ >>$USUARIO/log.txt 2>&1 ;
+     rm -rf $TMP/mcpe.zip;
      draw_progress_bar 10
 
     #config
     echo "Configuração Base"
-    rm -rf mcpe/server.properties >>$USUARIO/log.txt 2>&1 ;
-    rm -rf mcpe/whitelist.json >>$USUARIO/log.txt 2>&1 ;
-    cp -r ./server.properties mcpe/ >>$USUARIO/log.txt 2>&1 ;
-    cp -r ./whitelist.json mcpe/ >>$USUARIO/log.txt 2>&1 ;
+    rm -rf $TMP/mcpe/server.properties >>$USUARIO/log.txt 2>&1 ;
+    rm -rf $TMP/mcpe/whitelist.json >>$USUARIO/log.txt 2>&1 ;
+    cp -r $PASTA_PRINCIPALserver.properties mcpe/ >>$USUARIO/log.txt 2>&1 ;
+    cp -r $PASTA_PRINCIPALwhitelist.json mcpe/ >>$USUARIO/log.txt 2>&1 ;
 draw_progress_bar 15
     #Movendo
     echo "Criando e Movendo para o $PATH_TO_INSTALL"
@@ -127,10 +261,10 @@ draw_progress_bar 15
     draw_progress_bar 20
     mkdir $PATH_TO_INSTALL
     draw_progress_bar 30
-    cp -r mcpe/* $PATH_TO_INSTALL/
+    cp -r $TMP/mcpe/* $PATH_TO_INSTALL/
     draw_progress_bar 50
     echo "Limpando alguns arquivos"
-    rm -rf mcpe/
+    rm -rf $TMP/mcpe/
     echo "O log está no arquivo $USUARIO/log.txt"
     draw_progress_bar 100
 }
@@ -147,11 +281,11 @@ echo "$PATH_TO_BACKUP"
 mkdir "$PATH_TO_BACKUP"
 
 echo "verificando se a arquivos antingos no $(pwd)"
-if [[ -d mcpe/ ]]; then
-rm -rf mcpe/
+if [[ -d $TMP/mcpe/ ]]; then
+rm -rf $TMP/mcpe/
 fi
-if [[ -e mcpe.zip ]];then
-rm -rf mcpe.zip
+if [[ -e $TMP/mcpe.zip ]];then
+rm -rf $TMP/mcpe.zip
 fi
 draw_progress_bar 34
 
@@ -164,17 +298,17 @@ cd $voltando
 
 # BDS DOWNLOADS
 draw_progress_bar 48
-wget -q "$BDS" -O mcpe.zip
+wget -q "$BDS" -O $TMP/mcpe.zip
 
 # descompactando 
 draw_progress_bar 50
-unzip mcpe.zip -d mcpe > /dev/null
+unzip $TMP/mcpe.zip -d $TMP/mcpe > /dev/null
 
 # configurando
 if [ $? -eq 0 ];then
 echo "Whitelist.json"
-rm mcpe/whitelist.json
-cp $PATH_TO_BACKUP/whitelist.json mcpe/whitelist.json
+rm $TMP/mcpe/whitelist.json
+cp $PATH_TO_BACKUP/whitelist.json $TMP/mcpe/whitelist.json
 else
 echo "$?"
 echo "Saindo error ao extrair os arquivos"
@@ -183,8 +317,8 @@ fi
 
 if [ $? -eq 0 ];then
 echo "Server.properties"
-rm mcpe/server.properties
-cp $PATH_TO_BACKUP/server.properties mcpe/server.properties
+rm $TMP/mcpe/server.properties
+cp $PATH_TO_BACKUP/server.properties $TMP/mcpe/server.properties
 else
 echo "Saindo error no comando anterior"
 exit 127
@@ -192,8 +326,8 @@ fi
 
 if [ $? -eq 0 ];then
 echo "Mapas/Worlds"
-rm -r mcpe/worlds
-cp $PATH_TO_BACKUP/worlds mcpe/worlds
+rm -r $TMP/mcpe/worlds
+cp $PATH_TO_BACKUP/worlds $TMP/mcpe/worlds
 else
 echo "Saindo error no comando anterior"
 exit 127
@@ -205,7 +339,7 @@ mv -f $PATH_TO_INSTALL /tmp/
 fi
 
 #movendo
-cp -rf mcpe/* "$PATH_TO_INSTALL"
+cp -rf $TMP/mcpe/* "$PATH_TO_INSTALL"
 limpando
 }
 backupbysh23(){      
@@ -257,12 +391,12 @@ apache2-installbysh23(){
       read -rp "Qual é o nome que aparacera na pagina: " -e -i "$(cat /tmp/level.txt)" MAINSERVERNAME
 
       # Montando as Configurações
-      sed -i "s|ENDEREÇODOSERVIDOROUIP|$IPDOMAIN|g" "./html-files/index.html"
-      sed -i "s|MAINSERVERNAME|$MAPA_DO_SERVIDOR|g" "./html-files/index.html"
-      sed -i "s|PORTASERVER|$PORTAD|g" "./html-files/index.html"
+      sed -i "s|ENDEREÇODOSERVIDOROUIP|$IPDOMAIN|g" "$PASTA_PRINCIPALhtml-files/index.html"
+      sed -i "s|MAINSERVERNAME|$MAPA_DO_SERVIDOR|g" "$PASTA_PRINCIPALhtml-files/index.html"
+      sed -i "s|PORTASERVER|$PORTAD|g" "$PASTA_PRINCIPALhtml-files/index.html"
 
       # Movendo as configurações
-      cp -rf ./html-files/* /var/www/html/
+      cp -rf $PASTA_PRINCIPALhtml-files/* /var/www/html/
 }
 externobysh23(){
       
@@ -270,12 +404,12 @@ externobysh23(){
        apt install -y vsftpd samba >> /dev/null 2>&1 ;
 
       #config
-      sed -i "s|PATHTOISNTALL|$PATH_TO_INSTALL|g" "./smb.conf"
+      sed -i "s|PATHTOISNTALL|$PATH_TO_INSTALL|g" "$PASTA_PRINCIPALsmb.conf"
       sed -i "s|root||g" "/etc/ftpusers"
 
       rm /etc/samba/smb.conf
-      cp -rf ./smb.conf /etc/samba/
-      cp -rf ./vsftp.conf /etc/vsftpd.conf
+      cp -rf $PASTA_PRINCIPALsmb.conf /etc/samba/
+      cp -rf $PASTA_PRINCIPALvsftp.conf /etc/vsftpd.conf
 
       service smbd restart
       service vsftpd restart
@@ -296,7 +430,7 @@ fundobysh23(){
         rm -rf /usr/sbin/mcpe
         
             # -- Config --
-                cp fundo.sh /tmp/
+                cp $PASTA_PRINCIPALfundo.sh /tmp/
                 MINE2Sh23="/home/MCPE-Backups"
                 read -rp "Qual é o ID da pasta no google Drive caso fará backup para A Nuven (Exemplo: 1-FWzQJWhhJK_00ETU4uVOg6R5c5p_yMP)? " -e -i "" ID
                 read -rp "Aonde você vai quere colocar os Backups Locais (Caso queira)? " -e -i "$MINE2Sh23" MINE2Sh23
@@ -324,22 +458,22 @@ sistemabysh23(){
         rm -rf /tmp/level.txt
         
             # -- Config --
-                cp fundo.sh /tmp/
+                cp $PASTA_PRINCIPALfundo.sh /tmp/
                 MINE2Sh23="/var/www/html"
                 
-                if [[ -e IDs.txt ]];then
+                if [[ -e $TMP/IDs.txt ]];then
                 ID="$(cat IDs.txt)"
                 else
                     read -rp "Qual é o ID da pasta no google Drive caso fará backup para A Nuven (Exemplo: 1-FWzQJWhhJK_00ETU4uVOg6R5c5p_yMP)? " -e -i "" ID
                     echo "$ID" > IDs.txt
-                    dos2unix IDs.txt
+                    dos2unix $TMP/IDs.txt
                 fi
-                if [[ -e pasta.txt ]];then
+                if [[ -e $TMP/pasta.txt ]];then
                     MINE2Sh23="$(cat $HOME/pasta.txt)"
                 else
                     read -rp "Aonde você vai quere colocar os Backups Locais (Caso queira)? " -e -i "$MINE2Sh23" MINE2Sh23
-                    echo $MINE2Sh23 > pasta.txt
-                    dos2unix pasta.txt
+                    echo $MINE2Sh23 > $PASTA_PRINCIPALpasta.txt
+                    dos2unix $TMP/pasta.txt
                 fi
                 mkdir $MINE2Sh23
                 sed -i "s|IDSh23|$ID|g" "/tmp/fundo.sh";
@@ -351,13 +485,10 @@ sistemabysh23(){
             # -- Config --
     echo " "
     
-
-
-
     # ---------------------------------------
 
     echo "Iniciando as Configurações do arquivo para Inicialização junto com o Sistema"
-         cp start-on-system.sh /tmp/systemsh23.sh;
+         cp $PASTA_PRINCIPALstart-on-system.sh /tmp/systemsh23.sh;
             sed -i "s|IDSh23|$ID|g" "/tmp/systemsh23.sh";
             sed -i "s|MINESh23|$PATH_TO_INSTALL|g" "/tmp/systemsh23.sh";
             sed -i "s|NAMESh23|$MAPA_DO_SERVIDOR|g" "/tmp/systemsh23.sh";
@@ -382,10 +513,7 @@ update-rc.d BDS defaults-disabled
 update-rc.d BDS disable
 rm -rf /etc/init.d/BDS
 }
-#
-script-update(){
-      curl https://script.sirherobrine23.org/BDS-Script.sh | bash
-}
+
 crontabsh23(){
 
 
@@ -396,18 +524,18 @@ if [[ -e IDs.txt ]];then
 ID="$(cat IDs.txt)"
 else
     read -rp "Qual é o ID da pasta no google Drive caso fará backup para A Nuven (Exemplo: 1-FWzQJWhhJK_00ETU4uVOg6R5c5p_yMP)? " -e -i "" ID
-    echo "$ID" > IDs.txt
-    dos2unix IDs.txt
+    echo "$ID" > $PASTA_PRINCIPALIDs.txt
+    dos2unix $PASTA_PRINCIPALIDs.txt
 fi
-if [[ -e pasta.txt ]];then
-    MINE2Sh23="$(cat pasta.txt)"
+if [[ -e $PASTA_PRINCIPALpasta.txt ]];then
+    MINE2Sh23="$(cat $PASTA_PRINCIPALpasta.txt)"
 else
     read -rp "Aonde você vai quere colocar os Backups Locais (Caso queira)? " -e -i "$MINE2Sh23" MINE2Sh23
-    echo $MINE2Sh23 > pasta.txt
-    dos2unix pasta.txt
+    echo $MINE2Sh23 > $PASTA_PRINCIPALpasta.txt
+    dos2unix $PASTA_PRINCIPALpasta.txt
 fi
 mkdir $MINE2Sh23
-cp -rf backup-mcpe.sh /tmp/backup.sh
+cp -rf $TMP/backup-mcpe.sh /tmp/backup.sh
 sed -i "s|IDSh23|$ID|g" "/tmp/fundo.sh";
 sed -i "s|MINESh23|$PATH_TO_INSTALL|g" "/tmp/backup.sh";
 sed -i "s|NAMESh23|$MAPA_DO_SERVIDOR|g" "/tmp/backup.sh";
@@ -421,11 +549,19 @@ read -rp "De [ENTER] para continua" -e -i "" NULL
 crontab -e
 }
 
-
-# Escolha --------------  ***  -----------
 enable_trapping
-    # Create progress bar
-    setup_scroll_area
+setup_scroll_area
+
+if [[ -e /etc/bds-install/install.json ]];then
+json
+else
+echo "Por favor Adiciona install.json no /etc/bds-install/"
+fi
+root_acess
+if [[ $DESKTOP_GTK_SH23 = yes ]];then
+read -rp "oque vai quere fazer" -e -i "" 1
+fi
+
 case $1 in
 --install | -i )  installbysh23 ;;
 --update | -u ) updatebysh23 ;;
@@ -434,10 +570,8 @@ case $1 in
 --ip | -P ) ipbysh23 ;;
 --apache2 | --page | -a ) apache2-installbysh23 ;;
 --files | -f ) externobysh23 ;;
---update-script | -ds ) script-update ;;
 --remover-service | -R ) removerservicesh23 ;;
 --crontab | -c ) crontabsh23 ;;
---remover | -r )  rm -rf "$REMOVE";;
 --help | -h ) cat help.txt ; echo " ";;
 --teste ) echo "$0 $1 $2 $3 $4 $5";;
 *) echo "Exeute $0 --help - o comando $0 $1 não existe aqui";echo " "
